defaults: &defaults
  user: ironman
  pass: admin@123
  wsdlurl: http://localhost/rails_magento/dummy_magento/index.php/api/v2_soap?wsdl=1

development:
  <<: *defaults

test:
  <<: *defaults

production:
  user: ironman
  pass: admin@123
  wsdlurl: http://mywebdesignz.com/magento_store/index.php/api/v2_soap?wsdl=1